### ISSUE TITLE
#2 숙소 상세보기 페이지

### ISSUE THREAD

**Issue by ghost** [Fds17-FinalProject/SweetyPie_Frontend#2]
## 설명
> 숙소 상세보기 페이지 구현

## 작업 사항
- [x] 전체 레이아웃 구상해서 컴포넌트별로 분리하기 
- [x] Title 컴포넌트 구현
- [x] Photo 컴포넌트 구현
- [x] Introduction 컴포넌트 구현
- [x] Icons 컴포넌트 구현
- [x] Description 컴포넌트 구현
- [x] Beds 컴포넌트 구현
- [x] CalendarDetail 컴포넌트 구현
- [x] Payment 컴포넌트 구현
- [x] Reviews 컴포넌트 구현
- [x] ReviewProfile 컴포넌트 구현 
- [x] Map 컴포넌트 구현
- [x] Host 컴포넌트 구현
- [x] ThingsToKnow 컴포넌트 구현

**Comment by hanseul-lee** [comment]
숙소 상세보기 페이지 이슈 세부 단위로 쪼개서 수정하였습니다.
